force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductsControllerTest.cls
@isTest
public with sharing class ProductsControllerTest {

    @testSetup static void setup() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        List<Product__c> testProds = new List<Product__c>();
        for(Integer i=1;i<=5;i++) {
            testProds.add(new Product__c(
                Name = 'prod'+i,
                Description__c = 'test description ' + i,
                Type__c = ''+i,
                Family__c = ''+i,
                Price__c = 100
            ));
        }
        insert testProds;        
    }

    @isTest static void testGetAllProducts() {
        List<Product__c> lst = ProductsController.searchProducts('', new List<String>(), new List<String>());
        System.assertEquals(5, lst.size());
    }

    @isTest static void testSearchProducts() {
        List<Product__c> lst = ProductsController.searchProducts('prod', new List<String>{'1', '2'}, new List<String>{'1', '2'});
        System.assertEquals(2, lst.size());
    }
}