force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <label>OrderId</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductCartControllerTest.cls
@isTest
public with sharing class ProductCartControllerTest {

    @testSetup static void setup() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Account acc = new Account(
            Name = 'accName'
        );
        List<Product__c> testProds = new List<Product__c>();
        for(Integer i=1;i<=5;i++) {
            testProds.add(new Product__c(
                Name = 'prod'+i,
                Description__c = 'test description ' + i,
                Type__c = ''+i,
                Family__c = ''+i,
                Price__c = 100
            ));
        }
        insert testProds;  
        insert acc;        
    }

    @isTest static void testCreateOrder() {
        List<Product__c> lst = [SELECT Id, Name, Price__c FROM Product__c];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        ProductCartController.createOrder(lst, acc.Id);
        Order__c ord = [SELECT Id, AccountId__c FROM Order__c LIMIT 1];
        List<OrderItem__c> itemList = [SELECT Id, Name, OrderId__c FROM OrderItem__c WHERE OrderId__c = :ord.Id];
        System.assertEquals(acc.Id, ord.AccountId__c);
        System.assertEquals(5, itemList.size());
    }
}