force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <label>OrderId</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <label>ProductId</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProductCartController.cls
public with sharing class ProductCartController {
    
    @AuraEnabled(cacheable=false)
    public static String createOrder(List<Product__c> prodList, String accId) {
        Order__c newOrder = new Order__c(
            Name = accId + ' Order',
            AccountId__c = accId
        );
        insert newOrder;

        Map<Product__c, Integer> prodMap = new Map<Product__c, Integer>();
        for(Product__c prod : prodList){
            if(prodMap.get(prod) != null){
                prodMap.put(prod, prodMap.get(prod) + 1);
            }else{
                prodMap.put(prod, 1);
            }
        }
        List<OrderItem__c> orderLst = new List<OrderItem__c>();
        for(Product__c prod : prodMap.keySet()){
            orderLst.add(new OrderItem__c(
                OrderId__c = newOrder.Id,
                ProductId__c = prod.Id,
                Quantity__c = prodMap.get(prod),
                Price__c =  prodMap.get(prod) * prod.Price__c
            ));
        }
        insert orderLst;
        return newOrder.Id;
    }
}